DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Employee;

CREATE TABLE Department(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(25) NOT NULL
);

CREATE TABLE Role (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(25) NOT NULL,
    Salary DECIMAL NOT NULL, 
    DepartmentId INTEGER NOT NULL,
    CONSTRAINT User_Department FOREIGN KEY (DepartmentId)
    REFERENCES DepartmentId ON DELETE SET NULL
);


CREATE TABLE Employee (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    First_Name VARCHAR(25) NOT NULL,
    LastName VARCHAR(25 NOT NULL),
    RoleId INTEGER NOT NULL,
    ManagerId INTEGER NOT NULL,
    CONSTRAINT User_Role FOREIGN KEY (RoleId) REFERENCES Role(id) ON DELETE SET NULL,
    CONSTRAINT User_Manager FOREIGN KEY (ManagerId) REFERENCES Employee(id) ON DELETE SET NULL
);
